# A| Đánh giá mô hình phân lớp

## THỰC HÀNH 3.5
---


* Sinh viên xem lại bài thực hành 3.2 trong Chương 3 – phần 02 về phân loại rượu với thuật toán Decsion tree.
* Thực hiện xác định các tham số Accuracy, confusion matrix, Precision, Recall, F1-score với 2 trường hợp đã làm trên tập Test

In [2]:
#Đọc tập dữ liệu wine Dataset
import sklearn.datasets as datask
#Đọc dữ liệu trả về biến array
X_wine, y_wine = datask.load_wine(return_X_y=True)

print(type(X_wine))
print('Kích thước dữ liệu đầu vào (features):', X_wine.shape)
print('Kích thước dữ liệu đầu ra (target)   :', y_wine.shape)

<class 'numpy.ndarray'>
Kích thước dữ liệu đầu vào (features): (178, 13)
Kích thước dữ liệu đầu ra (target)   : (178,)


In [3]:
#Tách tập dữ liệu data_wine thành 2 phần train – test theo tỷ lệ 75% - 25%
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X_wine, y_wine, 
                                                    test_size=0.25, 
                                                    random_state=50)

print("1. Kích thước tập Training: %d" %len(y_train))
print("2. Kích thước tập Test    : %d" %len(y_test))

1. Kích thước tập Training: 133
2. Kích thước tập Test    : 45


In [4]:
#Gọi thư viên thuật toán DecisionTree
from sklearn.tree import DecisionTreeClassifier

#Xây dựng và huấn luyện với model: Decision Tree 
model_tree  = DecisionTreeClassifier(
                                     splitter='random', 
                                     random_state=0)
# Huấn luyên mô hình với dữ liệu huấn luyện
model_tree.fit(X_train, y_train)

DecisionTreeClassifier(random_state=0, splitter='random')

In [5]:
#Phân loại rượu trên tập kiểm thử với độ chính xác Accuracy
y_pred = model_tree.predict(X_test)

print("Kết quả phân loại rượu trên tập dữ liệu TEST:")
print("Predicted labels: ", y_pred)
print("Ground truth    : ", y_test)

from sklearn.metrics import accuracy_score
print("Độ chính xác đạt: %.2f %%" %(100*accuracy_score(y_test, y_pred)))

Kết quả phân loại rượu trên tập dữ liệu TEST:
Predicted labels:  [1 1 1 2 2 2 1 1 0 2 0 0 2 0 1 1 1 1 0 0 0 1 0 2 0 0 1 1 0 1 0 0 2 2 0 1 0
 2 0 0 1 1 1 2 1]
Ground truth    :  [1 1 1 2 2 2 1 1 0 2 0 0 1 0 1 2 1 2 1 0 0 1 0 2 0 0 1 1 0 1 0 0 2 2 0 1 1
 2 0 0 1 1 1 2 1]
Độ chính xác đạt: 88.89 %


In [6]:
# độ chính xác Accuracy Confusion Matrix
from sklearn.metrics import confusion_matrix
cnf_matrix = confusion_matrix(y_test, y_pred)
print('Confusion matrix:')
print(cnf_matrix)

Confusion matrix:
[[15  0  0]
 [ 2 16  1]
 [ 0  2  9]]


In [8]:
#độ chính xác Precision:
from sklearn.metrics import precision_score
precision = precision_score(y_test,
                            y_pred,                           
                            average=None)
print('Chỉ số Precision = ',precision)

Chỉ số Precision =  [0.88235294 0.88888889 0.9       ]


In [13]:
#độ chính xác Recall:
from sklearn.metrics import recall_score
recall = recall_score(y_test,
                        y_pred,                         
                        average=None)
print('Chỉ số recall = ',recall)

Chỉ số recall =  [1.         0.84210526 0.81818182]


In [28]:
#độ chính xác F1:
from sklearn.metrics import f1_score
f1 = f1_score(y_test,
              y_pred,                           
              average=None)
print('Chỉ số F1-score = ',f1)

Chỉ số F1-score =  [0.9375     0.86486486 0.85714286]


In [29]:
from sklearn.metrics import classification_report
target_names = ['class 0', 'class 1','class 3']
#Các thông số đánh giá bộ phân lớp:
print(classification_report(y_test, 
                            y_pred, 
                            target_names=target_names))

              precision    recall  f1-score   support

     class 0       0.88      1.00      0.94        15
     class 1       0.89      0.84      0.86        19
     class 3       0.90      0.82      0.86        11

    accuracy                           0.89        45
   macro avg       0.89      0.89      0.89        45
weighted avg       0.89      0.89      0.89        45



Sử dụng thuật toán Cây quyết định  trong 2 trường hợp:


* Sử dụng độ đo Entropy: Xác định độ chính xác của mô hình trên tập Test (25%).


In [18]:
#Gọi thư viên thuật toán DecisionTree
from sklearn.tree import DecisionTreeClassifier

#Xây dựng và huấn luyện với model: Decision Tree 
model_tree  = DecisionTreeClassifier(criterion= 'entropy', 
                                     splitter='random', 
                                     random_state=0)
# Huấn luyên mô hình với dữ liệu huấn luyện
model_tree.fit(X_train, y_train)

print("Độ chính xác của tập huấn luyện:",model_tree.score(X_train, y_train))

Độ chính xác của tập huấn luyện: 1.0


* Sử dụng độ đo Gini: Xác định độ chính xác của mô hình trên tập Test (25%).

In [19]:
#Gọi thư viên thuật toán DecisionTree
from sklearn.tree import DecisionTreeClassifier

#Xây dựng và huấn luyện với model: Decision Tree 
model_tree  = DecisionTreeClassifier(criterion= 'gini', 
                                     splitter='best', 
                                     random_state=0)
# Huấn luyên mô hình với dữ liệu huấn luyện
model_tree.fit(X_train, y_train)

print("Độ chính xác của tập huấn luyện:",model_tree.score(X_train, y_train))

Độ chính xác của tập huấn luyện: 1.0


# B| Đánh giá mô hình hồi quy

## THỰC HÀNH 3.6
---
* Sinh viên xem lại bài thực hành 3.3 trong Chương 3 – phần 03 về bài toán hồi quy với tập dữ liệu Diabetes Dataset .
* Xây dựng mô hình hồi quy tuyến tính với tất các thuộc tính đầu vào (input). Xác định sai số MAE, MSE, RMSE và R2  trên tập Train và Test.


In [19]:
#Đọc tập dữ liệu Iris Dataset
import sklearn.datasets as datask
#Đọc dữ liệu trả về biến array
X_diabetes, y_diabetes = datask.load_diabetes(return_X_y=True)

print(type(X_diabetes))
print('Kích thước dữ liệu đầu vào (features):', X_diabetes.shape)
print('Kích thước dữ liệu đầu ra (target)   :', y_diabetes.shape)

<class 'numpy.ndarray'>
Kích thước dữ liệu đầu vào (features): (442, 10)
Kích thước dữ liệu đầu ra (target)   : (442,)


In [36]:
# Biến X_diabetes: Lưu trữ 10 biến độc lập (input)
# Biến y_diabetes: Lưu trữ biến phụ thuộc (target)

from sklearn.model_selection import train_test_split
X_train_all, X_test_all, y_train, y_test = train_test_split(X_diabetes, 
                                                    y_diabetes, 
                                                    test_size=0.2, 
                                                    random_state=50)
print("1. Kích thước tập Training: %d" %len(y_train))
print("2. Kích thước tập Test    : %d" %len(y_test))

1. Kích thước tập Training: 353
2. Kích thước tập Test    : 89


In [37]:
X_train_all[:2,:]

array([[ 0.08166637,  0.05068012, -0.00297252, -0.03321358,  0.04246153,
         0.05787118, -0.01026611,  0.03430886, -0.00060925, -0.0010777 ],
       [-0.02730979, -0.04464164,  0.04768465, -0.04698506,  0.03420581,
         0.05724488, -0.08021722,  0.13025177,  0.04506617,  0.13146972]])

In [38]:
y_train[:2]

array([139., 317.])

In [39]:
#Sử dụng model hồi quy tuyến tính cho bài toán 
from sklearn.linear_model import LinearRegression
lin_model_all = LinearRegression(fit_intercept=True)# fit ứng với beta 0
lin_model_all.fit(X_train_all, y_train)

LinearRegression()

In [40]:
#Sử dụng model huẩn luyện được trên tập Train để dự đoán trên tập Test
y_pred_all = lin_model_all.predict(X_test_all)
print(y_pred_all)

[ 72.39635284  87.10241309 269.74341071  80.60898279  73.1741801
  42.89772697 154.94323987 186.45829394  97.94144538 137.63198912
 157.59342356 100.52649635 106.13055228  83.12440293 145.0406827
  81.78006479  77.23359572 151.17821453 160.40179413  92.54844233
 157.76025214 141.3471851  167.02455754 126.14443914 213.42218891
 163.7321554  158.26881524 121.53466999 125.78366562 245.05645831
 221.33030832 185.35779481  51.76587731  38.79576972  57.14817637
  36.5754586  155.4325103  123.60372691 165.12419399 133.48265513
 169.0497851  169.29376964 169.84942724 134.04805947 202.35285594
 178.64738173 122.20417974 179.58417758 173.16196243  53.74554589
 145.60364891  94.4883821  191.77812624 156.29583849  95.47593202
 161.81944759 125.2615453  217.02995874 120.04517998 245.56967689
 187.10682482 143.63594983  52.47871832 109.33917606 117.84453964
 157.11763121 167.28347065 163.00674797  68.66661974  69.06340111
 197.43509697 178.86362065  70.24282952 258.92528926 231.69535325
 138.2109480

In [41]:
# Sai số MAE
from sklearn.metrics import mean_absolute_error
mae = mean_absolute_error(y_test, y_pred_all)
print('Sai số  MAE = ', mae)

Sai số  MAE =  40.666784520508585


In [42]:
# Sai số MSE
from sklearn.metrics import mean_squared_error
mse = mean_squared_error(y_test, y_pred_all)
print('Sai số MSE = ', mse)

Sai số MSE =  2650.9384531241976


In [43]:
# Sai số RMSE
from sklearn.metrics import mean_squared_error
rmse = mean_squared_error(y_test,
                          y_pred_all,
                          squared=False)
print('Sai số RMSE = ', rmse)

Sai số RMSE =  51.487264960611355


In [44]:
# Sai số R2
from sklearn.metrics import r2_score
r2 = r2_score(y_test, y_pred_all)
print('Hệ số R^2 = ', r2)

Hệ số R^2 =  0.523408747228272
