In [1]:
#Đọc tập dữ liệu dataset
import pandas as pd
cancer = pd.read_csv('Data_Test.csv')
cancer.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 961 entries, 0 to 960
Data columns (total 5 columns):
 #   Column   Non-Null Count  Dtype  
---  ------   --------------  -----  
 0   Age      956 non-null    float64
 1   Shape    930 non-null    float64
 2   Margin   913 non-null    float64
 3   Density  885 non-null    float64
 4   Target   961 non-null    object 
dtypes: float64(4), object(1)
memory usage: 37.7+ KB


In [2]:
#Quan sát dữ liệu
cancer.describe()

Age       Shape      Margin     Density
count  956.000000  930.000000  913.000000  885.000000
mean    55.487448    2.721505    2.796276    2.910734
std     14.480131    1.242792    1.566546    0.380444
min     18.000000    1.000000    1.000000    1.000000
25%     45.000000    2.000000    1.000000    3.000000
50%     57.000000    3.000000    3.000000    3.000000
75%     66.000000    4.000000    4.000000    3.000000
max     96.000000    4.000000    5.000000    4.000000

In [3]:
#Kiểm tra dữ liệu thiếu trong dataset
cancer.isnull().sum()

Age         5
Shape      31
Margin     48
Density    76
Target      0
dtype: int64

In [4]:
#xóa những dữ liệu bị null
df_cancer = cancer.dropna()
df_cancer

Age  Shape  Margin  Density     Target
0    67.0    3.0     5.0      3.0  malignant
2    58.0    4.0     5.0      3.0  malignant
3    28.0    1.0     1.0      3.0     benign
8    57.0    1.0     5.0      3.0  malignant
10   76.0    1.0     4.0      3.0  malignant
..    ...    ...     ...      ...        ...
956  47.0    2.0     1.0      3.0     benign
957  56.0    4.0     5.0      3.0  malignant
958  64.0    4.0     5.0      3.0     benign
959  66.0    4.0     5.0      3.0  malignant
960  62.0    3.0     3.0      3.0     benign

[831 rows x 5 columns]

In [5]:
#Hiển thị dataframe mới sau khi đã xử lý dữ liệu null 
df_cancer.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 831 entries, 0 to 960
Data columns (total 5 columns):
 #   Column   Non-Null Count  Dtype  
---  ------   --------------  -----  
 0   Age      831 non-null    float64
 1   Shape    831 non-null    float64
 2   Margin   831 non-null    float64
 3   Density  831 non-null    float64
 4   Target   831 non-null    object 
dtypes: float64(4), object(1)
memory usage: 39.0+ KB


In [6]:
#Chuyển đổi thuộc tính Target về dạng số
convert_target = {'benign':0, 'malignant':1}
df_cancer['Target'] = df_cancer['Target'].map(convert_target).astype(int)
df_cancer.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 831 entries, 0 to 960
Data columns (total 5 columns):
 #   Column   Non-Null Count  Dtype  
---  ------   --------------  -----  
 0   Age      831 non-null    float64
 1   Shape    831 non-null    float64
 2   Margin   831 non-null    float64
 3   Density  831 non-null    float64
 4   Target   831 non-null    int32  
dtypes: float64(4), int32(1)
memory usage: 35.7 KB


<ipython-input-6-4a58ddeeff5d>:3: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_cancer['Target'] = df_cancer['Target'].map(convert_target).astype(int)


In [7]:
#Xác định biến phụ thuộc
y = df_cancer.iloc[:,4].values
y[:10]

array([1, 1, 0, 1, 1, 1, 0, 0, 0, 0])

In [8]:
#Xác định biến độc lập
X = df_cancer.iloc[:,0:4].values
X

array([[67.,  3.,  5.,  3.],
       [58.,  4.,  5.,  3.],
       [28.,  1.,  1.,  3.],
       ...,
       [64.,  4.,  5.,  3.],
       [66.,  4.,  5.,  3.],
       [62.,  3.,  3.,  3.]])

In [57]:
#Tách tập dưx liệu train - test tỉ lệ 75-25%
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.25, random_state = 0)
print("Kích thước tập train: ", X_train.shape)
print("Kích thước tập test: ", X_test.shape)

Kích thước tập train:  (623, 4)
Kích thước tập test:  (208, 4)


In [60]:
#Gọi thư viên thuật toán DecisionTree
from sklearn.tree import DecisionTreeClassifier

#Xây dựng và huấn luyện với model: Decision Tree 
model_tree  = DecisionTreeClassifier(criterion= 'gini', 
                                     splitter='best', 
                                     random_state=0)
model_tree.fit(X_train, y_train)

print("Độ chính xác của tập huấn luyện:",model_tree.score(X_train, y_train))

Độ chính xác của tập huấn luyện: 0.9149277688603531


In [61]:
y_pred = model_tree.predict(X_test)

print("Kết quả phân loại trên tập dữ liệu TEST:")
print("Predicted labels: ", y_pred)
print("Ground truth    : ", y_test)

from sklearn.metrics import accuracy_score
print("Độ chính đạt: %.2f %%" %(100*accuracy_score(y_test, y_pred)))

Kết quả phân loại trên tập dữ liệu TEST:
Predicted labels:  [1 1 0 0 0 0 0 1 1 1 0 0 1 0 0 0 0 0 0 1 0 1 0 0 1 0 1 1 0 0 0 0 0 0 0 0 1
 0 0 1 0 0 0 1 1 0 1 0 1 1 1 1 1 0 1 1 0 0 1 1 0 0 0 0 1 0 1 0 1 0 1 1 0 0
 1 1 0 1 1 1 0 1 0 0 0 1 1 1 0 0 1 1 1 0 1 1 0 1 1 0 1 1 0 0 0 1 0 1 1 0 1
 1 0 0 1 0 1 1 1 1 0 0 0 0 0 0 0 0 0 0 0 1 1 1 0 1 0 1 1 1 0 1 0 1 0 1 0 0
 0 1 0 0 1 1 0 0 1 0 0 0 0 0 1 1 1 0 0 0 1 1 1 1 0 0 1 0 1 0 1 1 1 1 1 0 0
 0 1 1 1 0 1 0 0 0 1 0 1 1 1 1 1 1 1 0 0 0 1 0]
Ground truth    :  [1 0 0 0 0 0 1 1 0 1 0 0 1 0 0 0 1 0 0 0 0 1 0 0 1 0 0 1 1 1 0 0 0 0 0 0 1
 0 1 0 0 1 0 1 1 1 1 0 1 1 1 1 1 1 1 0 0 0 0 1 1 0 0 0 1 0 1 0 1 0 1 1 0 0
 1 0 0 0 1 1 0 1 0 0 0 1 1 1 0 0 1 1 1 0 0 1 1 1 0 0 1 0 1 0 0 1 0 0 1 0 1
 1 1 1 1 0 1 1 1 1 1 0 0 1 0 1 0 0 0 0 0 1 1 1 1 1 0 0 1 1 0 0 0 1 0 1 0 1
 0 0 0 0 1 1 0 0 0 0 0 0 1 0 0 1 0 1 0 1 1 1 1 1 0 0 0 0 1 0 1 1 1 1 1 0 0
 1 0 1 0 0 1 1 0 1 1 1 1 1 1 1 1 1 1 0 0 0 1 0]
Độ chính đạt: 77.40 %


In [46]:
# xác định độ sau của cây: khoảng cách tối đã giữa gốc
print('Độ sâu của cây quyết đinh: ',model_tree.get_depth())

Độ sâu của cây quyết đinh:  18


In [47]:
#xác định số nút lá của cây quyết định
print('Số nút lá của cây quyết định: ', model_tree.get_n_leaves())

Số nút lá của cây quyết định:  172


In [48]:
# Hàm dự đoán
import numpy as np
def predicts(model_tree,Age,Shape,Margin,Density):
    cancer_new =np.array([[Age,Shape,Margin,Density]])
    pre = model_tree.predict(cancer_new)
    if pre == 0:
        print("Khối u của bạn là lành tính")
    else:
        print("Khối u của bạn là ác tính")
    return pre

In [56]:
Age = 29
Shape = 1
Margin = 1
Density = 2
predicts(model_tree,Age,Shape,Margin,Density)

Khối u của bạn là lành tính


array([0])